### ISSUE TITLE
Let's improve the exercise!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s2-evaluacion-intermedia-renrith#1]
Good job @renrith !!!

Here you have some tips to improve the exercise:

- [ ] Define the logic to make the counter work — good lateral thinking. This solution is creative enough, but we need to solve it the right way.
- [ ] Extract the feedback painter to a function
- [ ] Indent and avoid extra white spaces to improve readability and prevent bugs
- [ ] Try to improve your commit messages, better in English and using imperative. - > Fix central text

You are so close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by renrith** [comment]
Hello! I finally have some time to work on this, but I have a couple of questions:

- When it comes to the second point: if I understood this correctly, do I need to create another function to be activated inside the main function? That's what I've done for now, but asking just in case.

- I've solved a couple of indentation issues with auto indent. The thing is, I don't know which blank spaces are to be removed because of potential bugs and which aren't. I have removed some unnecessary spaces before () but I'm unsure how to proceed from here, specially because I do add some extra spacing on purpose to improve readability.

In any case, changes are submitted to a new branch (called enhancement).
